# Generated by Django 2.2.4 on 2019-09-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название экскурсии')),
                ('ticket_qty', models.IntegerField(verbose_name='Количество билетов')),
                ('time', models.TimeField(verbose_name='Время экскурсии')),
            ],
        ),
    ]
