# Generated by Django 2.1.7 on 2019-09-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilets', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cashier_surname',
            field=models.CharField(blank=True, max_length=100, verbose_name='ФИО Кассира'),
        ),
    ]
