# Generated by Django 2.1.7 on 2019-09-08 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilets', '0003_auto_20190908_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
