# Generated by Django 2.1.7 on 2019-09-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilets', '0004_auto_20190908_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='discount_ticket_price',
            field=models.IntegerField(default=22, verbose_name='Стоимость льготного билета'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='excursion',
            name='ticket_price',
            field=models.IntegerField(default=22, verbose_name='Стоимость обычного билета'),
            preserve_default=False,
        ),
    ]
