# Generated by Django 2.1.7 on 2019-09-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilets', '0006_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='excurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilets.Excursion', verbose_name='list of sites'),
        ),
    ]
