# Generated by Django 2.1.7 on 2019-09-08 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilets', '0008_auto_20190908_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='cashier',
            field=models.CharField(default=2, max_length=100, verbose_name='ФИ Кассира'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='discount_ticket',
            field=models.PositiveIntegerField(default=2, verbose_name='Количество льготных билетов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='free_ticket',
            field=models.PositiveIntegerField(default=3, verbose_name='Количество бесплатных билетов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickets',
            name='normal_ticket',
            field=models.PositiveIntegerField(default=34, verbose_name='Количество обычных билетов'),
            preserve_default=False,
        ),
    ]
