# Generated by Django 2.1.7 on 2019-09-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bilets', '0009_auto_20190908_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='excurs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bilets.Excursion', verbose_name='Экскурсия'),
        ),
    ]
