# Generated by Django 2.1.7 on 2019-09-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilets', '0010_auto_20190908_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursion',
            options={'verbose_name': 'Экскурсии'},
        ),
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name': 'Билеты'},
        ),
    ]
