# Generated by Django 2.1.7 on 2019-09-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bilets', '0011_auto_20190908_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursion',
            options={'verbose_name': 'Экскурсия', 'verbose_name_plural': 'Экскурсии'},
        ),
        migrations.AlterModelOptions(
            name='tickets',
            options={'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
    ]
