# Generated by Django 2.1.7 on 2019-09-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bilets', '0012_auto_20190908_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='ticket_pdf',
            field=models.FileField(default=1, upload_to='tickets_pdf/'),
            preserve_default=False,
        ),
    ]
